name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Building Frontend
        run: |
          npm i -g lerna
          npm i
          lerna bootstrap
          cd frontend
          npm run build
        env:
          # 因为最终部署地址为：https://feishou.gitee.io/bd7/ ，需要加一个 PUBLIC_URL
          PUBLIC_URL: /bd7

      - name: Publish Frontend to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/build
        # https://kevsoft.net/2020/06/10/running-github-action-steps-and-jobs-only-on-push-to-master.html
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:techtrainingcamp-frontend-7/BD7.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:feishou/bd7.git
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: feishou
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: feishou/bd7
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: gh-pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - name: Publish Backend to Vercel
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 源仓库地址
          source-repo: git@github.com:techtrainingcamp-frontend-7/BD7.git
          # 目标仓库地址
          destination-repo: git@github.com:upupming/BD7.git
